# Generated by Django 5.2 on 2025-05-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('publication_year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('custom_category', models.CharField(blank=True, max_length=100, null=True)),
                ('book_condition', models.CharField(choices=[('new', 'New'), ('like-new', 'Like New'), ('good', 'Good'), ('acceptable', 'Acceptable')], max_length=50)),
                ('description', models.TextField()),
                ('book_cover_image', models.ImageField(upload_to='book_covers/')),
                ('book_document', models.FileField(blank=True, null=True, upload_to='book_documents/')),
                ('email', models.EmailField(max_length=254)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('no_of_downloads', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
