# Generated by Django 5.2 on 2025-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDetails', '0002_book_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
