# Generated by Django 5.2 on 2025-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksDetails', '0003_remove_book_id_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
